### ISSUE TITLE
如何获取相似度更高的两个语句

### ISSUE THREAD

**Issue by Jothangan** [terrifyzhao/bert-utils#15]
通过这个方式获取到相似度值，要么无限趋近于0，要么无限趋近于1。项目中有需求判断语句A和语句B相似度是否高于语句A和语句C的相似度，测试后效果并不好，如下：
sentenceA：世界上世界上拥有摩天大楼最多的国家  sentenceB：世界上世界上拥有摩天大楼最多的国家 score:  0.9999398
sentenceA：世界上世界上拥有摩天大楼最多的国家  sentenceC：世界上世界摩天大楼最多的城市 score:  0.99997306

**Comment by terrifyzhao** [comment]
bert不是万能的，建议结合其他方法一起解决该问题

**Comment by 18813055625** [comment]
@terrifyzhao  为什么每次计算文本相似度的时候都重新build graph?

**Comment by 18813055625** [comment]
@terrifyzhao  为什么每次计算文本相似度的时候都重新build graph?

**Comment by yangyan1227** [comment]
什么意思？怎么用这个模型获取两个文本的相似度呢




| |
18742521993
邮箱：18742521993@163.com
|

Signature is customized by Netease Mail Master

在2019年09月06日 16:04，18813055625 写道：

@terrifyzhao 为什么每次计算文本相似度的时候都重新build graph?

**Comment by xxllp** [comment]
真弱鸡啊

**Comment by Jothangan** [comment]
不需要继续讨论
