### ISSUE TITLE
Floating point exception  and  SystemError: error return without exception set

### ISSUE THREAD

**Issue by yongzhuo** [terrifyzhao/bert-utils#20]
Floating point exception (core dumped) when running extract_feature.py using linux、tensorflow-gpu==1.12.0
and
SystemError: error return without exception set when debug with windows 10.
zhao, what we need is your help。。。。。。
crying

**Comment by terrifyzhao** [comment]
@yongzhuo 貌似是cuda的问题，试试cpu版本

**Comment by yongzhuo** [comment]
where i change tf to keras. it is ok !
project:  [https://github.com/CyberZHG/keras-bert](https://github.com/CyberZHG/keras-bert)
demo: [https://github.com/CyberZHG/keras-bert/blob/master/demo/load_model/load_and_pool.py](https://github.com/CyberZHG/keras-bert/blob/master/demo/load_model/load_and_pool.py)
I think there was something with the graph of queue, maybe it is wrong with shareing  the graph. 
or we couldn't use queue it in one single gpu? when using keras called by django, first it wasn't work for "tensor *** is not an element in the graph."  we use "global model"、"global gragh" ， it success!

**Comment by terrifyzhao** [comment]
@yongzhuo 卓哥，你真调皮
