### ISSUE TITLE
用此代码跑eval的时候出现的问题

### ISSUE THREAD

**Issue by Venut-yjc** [terrifyzhao/bert-utils#21]
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [predictions must be in [0, 1]] [Condition x <= y did not hold element-wise:x (ArgMax:0) = ] [119 119 119...] [y (auc/Cast_1:0) = ] [1]

你好，我在运行你的代码的时候，在进行eval的时候，出现了这个问题是怎么回事？

**Comment by 625033011** [comment]
你好请问解决了吗
