### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by ZJUHSY** [terrifyzhao/bert-utils#24]
Hello! I just run this file in jupyter notebook,but it seemed that the zip file added to jupyter notebook can not be encoded to UTF-8, how can I solve this problem? Thansks!

**Comment by terrifyzhao** [comment]
@ZJUHSY 
do you unzip your file?

**Comment by ZJUHSY** [comment]
The problem is solved


发自我的iPhone

------------------ Original ------------------

**Comment by ZJUHSY** [comment]
Thanks


发自我的iPhone

------------------ Original ------------------
