### ISSUE TITLE
同时启动两个Bert对象出错

### ISSUE THREAD

**Issue by cdj0311** [terrifyzhao/bert-utils#29]
我需要启动两个max_seq_len不一样的Bert对象（一个是100，另一个是300），报如下错“ValueError: Requested return tensor 'final_encodes:0' not found in graph def
”请问是怎么回事呢？我用bert-as-service就没有这个问题。

**Comment by terrifyzhao** [comment]
@cdj0311 的确存在这个问题，有空我会尽快修复

**Comment by terrifyzhao** [comment]
@cdj0311 已修复

**Comment by cdj0311** [comment]
@terrifyzhao 非常感谢，赞！
