### ISSUE TITLE
修改args max_seq_len后报错

### ISSUE THREAD

**Issue by zachkang** [terrifyzhao/bert-utils#43]
如题修改max_seq_len参数后报错，请问是否还需要修改其他地方？

ValueError: Dimensions must be equal, but are 5 and 128 for 'import/mul' (op: 'Mul') with input shapes: [?,5,768], [?,128,1].

**Comment by zachkang** [comment]
fixed.

**Comment by bytetopia** [comment]
请问是怎么解决的呢？

**Comment by bytetopia** [comment]
> 请问是怎么解决的呢？

发现原因了😰 因为第一次运行时构建了维度为5的图存到tmp里了，之后直接从tmp加载的，所以出现了维度对不上的情况，删掉tmp里的graph就行了…………
