### ISSUE TITLE
一次塞入多个句子，循环生成句向量时出错

### ISSUE THREAD

**Issue by ARSblithe212** [terrifyzhao/bert-utils#50]
一次塞入多个句子，当循环到第二次时，程序就卡住无法返回句向量。

**Comment by FisherOuch** [comment]
我也遇到了这个问题，将queue_predict_input_fn中label_ids的shape从 (1,) 改成 (None,) 就可以使label_id传入多个了。

**Comment by ARSblithe212** [comment]
> 我也遇到了这个问题，将queue_predict_input_fn中label_ids的shape从 (1,) 改成 (None,) 就可以使label_id传入多个了。
