### ISSUE TITLE
加载过graph后，还是比较慢，所需时间是 bert-as-service的20倍，这是为什么？

### ISSUE THREAD

**Issue by zhouyongjie** [terrifyzhao/bert-utils#67]
我采用单个句子，进行了时间的测试，作者的方法需要 0.012s，bert-as-service需要0.0006s，代码结构相同，bert-as-service是有在哪里做了优化吗？

**Comment by pandab0y** [comment]
请问你解决了效率问题吗

**Comment by zhouyongjie** [comment]
> 请问你解决了效率问题吗
还没有，不过我提出的这个问题解决了，bert-as-service的cpu运行时间较快，但是系统时间与作者的方法几乎一致
