### ISSUE TITLE
对sentence进行相似度预测时输入分词错误

### ISSUE THREAD

**Issue by LawrenceGK** [terrifyzhao/bert-utils#68]
![image](https://user-images.githubusercontent.com/37487354/93038062-94b9cd80-f676-11ea-95c4-608440b3f1e6.png)
另外在采用英文输入进行测试时有以下状况
INPUT：“hello world” "hello world"
OUTPUT："[CLS] hello [SEP] hello [SEP]"

**Comment by LawrenceGK** [comment]
args里max_seq_len设置是5，bert自己做的截断

**Comment by Lawgk** [comment]
args里max_seq_len设置是5，bert自己做的截断
