### ISSUE TITLE
如何只打印句向量

### ISSUE THREAD

**Issue by wingsyuan** [terrifyzhao/bert-utils#7]
您好，看了您代码后，受益匪浅，谢谢大佬的辛勤付出和分享！

这里能否问一个问题，我想打印出所生成的句向量，如下：

      with tf.gfile.GFile(tmp_file, 'wb') as f:
            f.write(tmp_g.SerializeToString())
            print(tmp_g.SerializeToString())
但看起来它非常大，请问是什么原因呢，每一个句子都可以转化成固定长度的词向量对吗，它的长度有多大？如何只打印出句向量呢？

**Comment by terrifyzhao** [comment]
隐层的节点是768个，所以生成的句向量是768维的，每一个句子生成的句向量都是768维，更多细节请参阅我的[blog](https://blog.csdn.net/u012526436/article/details/87697242)

**Comment by wingsyuan** [comment]
@terrifyzhao 
我看了您的博客了，也明白上面的意思，谢谢大佬！但如您所说您把句向量和计算图写到temp文件中了，在graph代码中我不知道哪一部分是纯粹句向量的，我只想打印出句向量？请问是print哪一个变量呢。。非常感谢您的回复！

**Comment by wingsyuan** [comment]
config = tf.ConfigProto(allow_soft_placement=True)
        with tf.Session(config=config) as sess:
            logger.info('load parameters from checkpoint...')
            sess.run(tf.global_variables_initializer())
            logger.info('freeze...')
            **tmp_g = tf.graph_util.convert_variables_to_constants(sess, tmp_g, [n.name[:-2] for n in output_tensors])**请问是这一句吗？ 谢谢指导。。
            
            dtypes = [n.dtype for n in input_tensors]
            logger.info('optimize...')
            tmp_g = optimize_for_inference(
                tmp_g,
                [n.name[:-2] for n in input_tensors],
                [n.name[:-2] for n in output_tensors],
                [dtype.as_datatype_enum for dtype in dtypes],
                False)
        tmp_file = tempfile.NamedTemporaryFile('w', delete=False, dir=args.output_dir).name
        logger.info('write graph to a tmp file: %s' % tmp_file)
        with tf.gfile.GFile(tmp_file, 'wb') as f:
            f.write(tmp_g.SerializeToString())
            print(output_tensors)
        return tmp_file

**Comment by wingsyuan** [comment]
@terrifyzhao 
请问打印下面哪一部分可以直接得到句向量表示？谢谢
with tf.Session(config=config) as sess:
            logger.info('load parameters from checkpoint...')
            sess.run(tf.global_variables_initializer())
            logger.info('freeze...')
            tmp_g = tf.graph_util.convert_variables_to_constants(sess, tmp_g, [n.name[:-2] for n in output_tensors])
            dtypes = [n.dtype for n in input_tensors]
            logger.info('optimize...')
            tmp_g = optimize_for_inference(
                tmp_g,
                [n.name[:-2] for n in input_tensors],
                [n.name[:-2] for n in output_tensors],
                [dtype.as_datatype_enum for dtype in dtypes],
                False)
        tmp_file = tempfile.NamedTemporaryFile('w', delete=False, dir=args.output_dir).name
        logger.info('write graph to a tmp file: %s' % tmp_file)
        with tf.gfile.GFile(tmp_file, 'wb') as f:
            f.write(tmp_g.SerializeToString())       
        return tmp_file
    except Exception as e:
        logger.error('fail to optimize the graph!')
        logger.error(e)

**Comment by wingsyuan** [comment]
@terrifyzhao 
请问，是打印下面的output_tensor或pooled么，如果是要怎么打印出来，用各种方法都报错。。
  # 以下代码是句向量的生成方法，可以理解为做了一个卷积的操作，但是没有把结果相加, 卷积核是
input_mask
            pooled = masked_reduce_mean(encoder_layer, input_mask)
            pooled = tf.identity(pooled, 'final_encodes')           
            output_tensors = [pooled]
            #with tf.Session():  
             #   print(output_tensors.eval())
