### ISSUE TITLE
运行extract-feature.py时遇到的问题。

### ISSUE THREAD

**Issue by HenryWInfinity** [terrifyzhao/bert-utils#76]
![image](https://user-images.githubusercontent.com/62539043/128212984-6b928620-2715-4625-9e0d-f64caacaa808.png)
怎么弄，球球了！

**Comment by HenryWInfinity** [comment]
我是傻逼，把tensorflow版本降下来就行了。

**Comment by Knightzhr** [comment]
麻烦问一下，tensorflow的版本降到多少就行了
