### ISSUE TITLE
缺少相关配置文件

### ISSUE THREAD

**Issue by li-jp** [terrifyzhao/bert-utils#77]
tensorflow.python.framework.errors_impl.NotFoundError: ./bert-utils/chinese_L-12_H-768_A-12/vocab.txt; No such file or directory
项目里没有找到这个词表，是不是在更新代码的时候被剔掉了

**Comment by myinvoke** [comment]
下载BERT中文模型
下载地址: https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip
里面数据都全的
